web/jsf_demo/src/main/java/com/nick/mbean/SomeBean.java
package com.nick.mbean;

import javax.faces.bean.ManagedBean;

@ManagedBean
public class SomeBean {
    
    private String someProperties = "Blah, blah";
    
    public String getSomeProperty() {
        return someProperties;
    }
    
    public void setSomeProperty(String sp) {
        this.someProperties = sp;
    }
    
    public String someActionControllerMethod() {
        return "accordion_panel";
    }
    
    public String someOtherActionControllerMethod() {
        return "index";
    }

}

web/jsf_demo/src/main/webapp/accordion_panel.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:body>
<p:accordionPanel>
    <p:tab title="First Tab Title">
        <h:outputText value="Lorem"/>
        ...More content for first tab
    </p:tab>
    <p:tab title="Second Tab Title">
        <h:outputText value="Ipsum"/>
    </p:tab>
</p:accordionPanel>
</h:body>
</html>

web/jsf_demo/src/main/webapp/index.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3c.org/1999/xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:body>
<div align="center">
    <fieldset>
        <legend>JSF Test Form</legend>
        <h:form>Some random data: <h:inputText value="#{someBean.someProperty}"/>
            <h:commandButton value="Go to Page Accordion Panel" action="#{someBean.someActionControllerMethod}"/>
        </h:form>
    </fieldset>
</div>

<p:editor />
</h:body>
</html>